global.random.strong=true
global.banner=false
global.pepper=APP_PEPPER
hash.argon2.memory=47104
hash.argon2.iterations=2
hash.argon2.length=64
hash.argon2.parallelism=2
hash.argon2.type=id
hash.argon2.version=19